# Generated by Django 3.0.6 on 2020-05-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FileField(upload_to='media/%Y/%m/%d/')),
                ('name', models.CharField(max_length=200, verbose_name='Username')),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('date_entry_plataform', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
